### ISSUE TITLE
No A-Pro Editor on Linux

### ISSUE THREAD

**Issue by bzhr** [Suloo/Cakewalk-A-300-PRO#1]
I am using Linux and Bitwig recognizes the midi (notes can be played, but it isn't found in recognized midi devices), but I cannot do step number 2 because the Roland driver is for mac/windows.

I copied the script to /Controller Scripts/, but the controls do not work.
I suppose it is because I cannot do step number 2.
Do you have an idea how to solve this?
Or maybe I can learn the controls myself because there aren't too many?

**Comment by mkschulze** [comment]
Hello,  
I would suggest to find a win/Mac machine to load up the file. Or maybe use a virtual installation. You could learn most controls I think, but i‘m Not sure if all of the transport controls can be learned. You can look into the script, the variables in the beginning reflect the CC numbers. However, i think uploading the file would be better. 

Good luck!

**Comment by bzhr** [comment]
Hello,

Thank you for the answer. Yes I can use my old macbook to load the file and then try it from Bitwig on Linux. Didn't think of that!
